export const HOME = {
  MAIN_PAGE: {
    ACCOUNT_TAB: "#tabAccount",
    BASKET_BUTTON: "#basket-overview",
    CATALOGUE_OPTIONS: ".dropdown-menu a",
    CATALOGUE_TAB: "#tabCatalogue",
    LOGGEDIN_LINK: "#howdy",
    LOGIN_LINK: "#login a",
    LOGOUT_LINK: "#logout a",
    REGISTER_LINK: "#register a",
    TOP_CONTAINER: "#top",
  },
  LOGIN_MODAL: {
    CLOSE_BUTTON: ".close",
    HEADER: "#Login",
    LOGIN_BUTTON: ".btn-primary",
    MESSAGE: "#login-message",
    MODAL: "#login-modal .modal-content",
    PASSWORD: "#password-modal",
    USERNAME: "#username-modal",
  },
  REGISTER_MODAL: {
    CLOSE_BUTTON: ".close",
    EMAIL: "#register-email-modal",
    FIRST_NAME: "#register-first-modal",
    HEADER: "#Login",
    LAST_NAME: "#register-last-modal",
    MESSAGE: "#registration-message",
    MODAL: "#register-modal .modal-content",
    PASSWORD: "#register-password-modal",
    REGISTER_BUTTON: ".btn-primary",
    USERNAME: "#register-username-modal",
  },
};
